version: 2
jobs:
  build-job:
    docker:
      - image: google/dart
    steps:
      - checkout
      - run:
          name: "dart circleci firebase"
          command: echo Dart circleci
      - run:
          name: Print the current time
          command: date
      - run: dart --version
      - run: pub get
      - run: dart --version
      - run: pub get
      - run: pub build
      - run: ls -al
      - persist_to_workspace:
          root: .
          paths: build
  deploy-job:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run: node --version
      - run: npm --version
      - run: pwd
      - run: ls -al
      - run: npm init
      - run: npm install --save-dev firebase-tools
      - run: firebase login --email amelieelibh@gmail.com --password SakurA01
      - run: firebase deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
              