version: 2
jobs:
  docker:
    - image: google/dart
  working_directory: ~/web
  steps:
    - checkout
    - run:
      name: "dart circleci firebase"
      command: echo Dart circleci
    - run:
      name: Print the current ti,e
      command: date

general:
  branches:
    only:
      - master

test:
  override:
    - echo "test"

deployment:
  production:
    branch: master
    commands:
      - npm install -g firebase-tools
      - firebase login --email amelieelibh@gmail.com --password SakurA01
      - firebase deploy