version: 2
jobs:
  build-job:
    docker:
      - image: google/dart
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "dart circleci firebase"
          command: echo Dart circleci
      - run:
          name: Print the current ti,e
          command: date
      - run: dart --version
      - run: pub get
      - run: dart --version
      - run: pub get
      - run: pub build
  deploy-job:
    docker:
      - image: circleci/node
    working_directory: ~/project
    dependencies:
      
    steps:
      - run: node --version
      - run: npm --version
      - run: npm install --save-dev firebase-tools
      - run: firebase login --email amelieelibh@gmail.com --password SakurA01
      - run: firebase deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
              