version: 2
jobs:
  build:
    docker:
      - image: google/dart
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "dart circleci firebase"
          command: echo Dart circleci
      - run:
          name: Print the current ti,e
          command: date
      - run: dart --version
      - run: pub get
      - run: dart --version
      - run: pub get
      - run: pub build
      - persist_to_workspace:
          root: /root/project
          paths: src/public/
  deploy:
    docker:
      - image: google/dart
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /root/project
      - run: npm install -g firebase-tools
      - run: firebase login --email amelieelibh@gmail.com --password SakurA01
      - run: firebase deploy