version: 2
jobs:
  build-job:
    working_directory: ~/cci-sdc
    docker:
      - image: google/dart
    steps:
      - checkout
      - attach_workspace:
          at: ~/cci-sdc
      - run: dart --version
      - run: pub get
      - run: dart --version
      - run: pub get
      - run: pub build
      - run: pwd
      - run: ls -a
#      - run: git add -f build
#      - run: git config --global user.email "$US_EMAIL"
#      - run: git config --global user.name "$US_NAME"
#      - run: git commit -m 'circleci build'
#      - run: git push -f origin master
      - persist_to_workspace:
          root: ..
          paths: cci-sdc
#      - persist_to_workspace:
#          root: .
#          paths: package.json
  deploy-job:
    working_directory: ~/cci-sdc
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          #at: ~/cci-sdc
          at: /home/circleci/
#      - checkout
      - run: node --version
      - run: npm --version
      - run: pwd
      - run: ls -a
      - run: ls -a ..
      #- run: ls -a cci-sdc
      #- run: cd cci-sdc
      - run: sudo npm install -g firebase-tools
      #- run: npm get prefix
      - run: ls /usr/local/bin
      - run: echo $PATH
      #- run: ls /usr/local/npm/bin
      #- run: alias firebase="'npm config get prefix'/bin/firebase"
      - run: firebase -version
      - run: firebase login --email $US_EMAIL --password $US_PASS
      - run: firebase deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master              
        
