version: 2
jobs:
  build:
    machine:
      node:
        versiom: 8.0.0
    docker:
      - image: google/dart
      - image: circleci/node
    dependencies:
        - node --version
        - npm --version
        - dart --version
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "dart circleci firebase"
          command: echo Dart circleci
      - run:
          name: Print the current ti,e
          command: date
      - run: dart --version
      - run: pub get
      - run: dart --version
      - run: pub get
      - run: pub build
      - run: npm install -g firebase-tools
      - run: firebase login --email amelieelibh@gmail.com --password SakurA01
      - run: firebase deploy
      - persist_to_workspace:
          root: /root/project
          paths: build
  deploy:
    docker:
      - image: circleci/node
    machine:
        enabled: true
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /root/project
      - run: npm install -g firebase-tools
      - run: firebase login --email amelieelibh@gmail.com --password SakurA01
      - run: firebase deploy